spring:
  application:
    name: payments

  datasource:
    url: jdbc:postgresql://localhost:5432/psql_labs
    username: psql_labs_owner
    password: psql_labs_owner_password

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8082