spring:
  application:
    name: payments

  datasource:
    url: jdbc:postgresql://localhost:5432/psql_labs
    username: psql_labs_owner
    password: psql_labs_owner_password

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true