spring:
  application:
    name: shared

  datasource:
    url: jdbc:postgresql://localhost:5432/psql_labs
    username: psql_labs_owner
    password: psql_labs_owner_password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always