spring:
  application:
    name: open-exchange

  datasource:
    url: jdbc:postgresql://localhost:5432/psql_labs
    username: psql_labs_owner
    password: psql_labs_owner_password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always

  cloud:
    stream:
      bindings:
        processPayment-in-0:
          destination: payments-to-process
          group: consumer
      default:
        consumer:
          use-native-decoding: false
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            spring.json.trusted.packages: '*'
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8083

currency:
  api:
    url: https://openexchangerates.org/api/latest.json?app_id=
    appID: 91b5cf4798104d5193b426f43c693158