spring:
  application:
    name: open-exchange

  datasource:
    url: jdbc:postgresql://localhost:5432/psql_labs
    username: psql_labs_owner
    password: psql_labs_owner_password

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG

currency:
  api:
    url: https://openexchangerates.org/api/latest.json?app_id=
    appID: 91b5cf4798104d5193b426f43c693158

server:
  port: 8083